apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2  # "123456" en Base64
  MYSQL_PASSWORD: MTIzNDU2  # "123456" en Base64
  SPRING_DATASOURCE_PASSWORD: MTIzNDU2  # "123456" en Base64
  DB_PASSWORD: MTIzNDU2  # Para NestJS