apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  MYSQL_DATABASE: "genosentinel"
  MYSQL_USER: "root"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/genosentinel"
  SPRING_DATASOURCE_USERNAME: "root"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_DATABASE: "genosentinel"