# Generated by Django 5.2.8 on 2025-11-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('function_summary', models.TextField()),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('reference_base', models.CharField(max_length=1)),
                ('alternate_base', models.CharField(max_length=1)),
                ('impact', models.CharField(max_length=20)),
                ('gene', models.ForeignKey(db_column='gene_id', on_delete=django.db.models.deletion.CASCADE, to='genoma.gene')),
            ],
            options={
                'db_table': 'genetic_variant',
            },
        ),
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.BigIntegerField()),
                ('detection_date', models.DateField()),
                ('allele_frequency', models.DecimalField(decimal_places=3, max_digits=4)),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, to='genoma.geneticvariant')),
            ],
            options={
                'db_table': 'patient_variant_report',
            },
        ),
    ]
