# Generated by Django 5.2.8 on 2025-11-25 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0001_initial'),
    ]

    operations = [
   
    ]
