# Generated by Django 5.2.8 on 2025-11-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0002_alter_patientvariantreport_allele_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvariantreport',
            name='allele_frequency',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='patientvariantreport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientvariantreport',
            name='patient_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patientvariantreport',
            name='variant',
            field=models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, to='genoma.geneticvariant'),
        ),
        migrations.AlterModelTable(
            name='patientvariantreport',
            table='patient_variant_report',
        ),
    ]
