# Generated by Django 5.2.8 on 2025-11-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0003_alter_patientvariantreport_allele_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvariantreport',
            options={'managed': False},
        ),
    ]
